name: Generate PDF

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '10.2.4'

    - name: Install dependencies
      run: |
        cd docs
        npm -v
        npm install
        npm start &

    - name: Start server
      run: |
        cd docs
        npm start &

    - name: Wait for server to start
      run: sleep 10

    - name: Generate PDF
      run: |
        npm install -g decktape
        decktape --slides 1-25 automatic http://localhost:9000 ./presentation-slides.pdf

    - name: Commit and push PDF
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add presentation-slides.pdf
        git commit -m "Add generated PDF"
        git push
